# Generated by Django 4.1.4 on 2022-12-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_delete_medicinedetails_alter_medicinerecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='medicine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicine.medicinename'),
        ),
    ]
