# Generated by Django 4.1.4 on 2022-12-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicinename_alter_medicinerecord_medicine_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinename',
            options={'verbose_name_plural': 'Medicine Name'},
        ),
    ]
