# Generated by Django 4.1.4 on 2022-12-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_medicinename_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SavedMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.IntegerField()),
                ('timeof', models.BooleanField()),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicine.medicinename')),
                ('time', models.ManyToManyField(to='medicine.medicinetime')),
            ],
        ),
    ]
