# Generated by Django 4.1.4 on 2022-12-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_medicinetime_medicinetype_savedmedicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedmedicines',
            name='timeof',
        ),
        migrations.AddField(
            model_name='savedmedicines',
            name='intake',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
