# Generated by Django 4.1.4 on 2022-12-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_savedmedicines_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmedicines',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicine.medicinetype'),
        ),
    ]
