# Generated by Django 4.1.4 on 2022-12-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_savedmedicines_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedmedicines',
            name='time',
        ),
        migrations.DeleteModel(
            name='MedicineTime',
        ),
    ]
