# Generated by Django 4.1.4 on 2022-12-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_remove_savedmedicines_time_delete_medicinetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmedicines',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
