# Generated by Django 4.1.4 on 2022-12-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_savedmedicines_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmedicines',
            name='time',
            field=models.TimeField(),
        ),
    ]
